
server:
  servlet:
    context-path: '/api'
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  flyway:
    url: jdbc:h2:mem:testdb
    user: sa
    password: password
    locations: classpath:db/migration
    schemas: people
