server:
  servlet:
    context-path: '/api'
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/people
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: pass
  flyway:
    url: jdbc:mysql://localhost:3308/people
    user: root
    password: pass
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
